### ISSUE TITLE
Download datasets

### ISSUE THREAD

**Issue by cyh03223** [Jin-Ying/Multi-Level-Logit-Distillation#9]
I was trying to downloads the dataset you given in README (CIFAR-100 & ImageNet), however, I can't find both of paths.
Would you like to state the download bash commands so I can directly download them for reproduce result. Thanks.

**Comment by Jin-Ying** [comment]
First, I think the Cifar-100 is downloaded automatically. 
For ImageNet, my version is ImageNet-2012, per folder per category. I have not tried to download it. But you can try to download it here, https://image-net.org/challenges/LSVRC/index.php.
